### ISSUE TITLE
sr查询信息出错

### ISSUE THREAD

**Issue by 23650** [qwerdvd/StarRailUID#13]
如下：
05-13 23:15:24 [INFO] gsuid_core.handler | [Raw] raw_text=sr查询信息, image=None, at=None, image_list=None, at_list=[], is_tome=False, reply=None, file_name=None, file_type=None, file=None | [Receive] bot_id=onebot, bot_self_id=+++++++, msg_id=-++++++++, user_type=group, group_id=+++++++, user_id=++++++++, user_pm=1, content=[Message(type='text', data='sr查询信息')],
05-13 23:15:24 [INFO] gsuid_core.handler | [Trigger] 消息 「sr查询信息」 触发 「prefix」 类型触发器, 关键词: 「sr查询」
05-13 23:15:24 [INFO] gsuid_core.handler | [Command] command=sr查询, text=信息
Task exception was never retrieved
future: <Task finished name='Task-3365' coro=<send_char_info() done, defined at E:\zhenxun\gsuid_core\gsuid_core\plugins\StarRailUID\StarRailUID\starrailuid_charinfo\__init__.py:23> exception=KeyError('')>
Traceback (most recent call last):
  File "E:\zhenxun\gsuid_core\gsuid_core\plugins\StarRailUID\StarRailUID\starrailuid_charinfo\__init__.py", line 25, in send_char_info
    im = await _get_char_info(bot, ev, ev.text)
  File "E:\zhenxun\gsuid_core\gsuid_core\plugins\StarRailUID\StarRailUID\starrailuid_charinfo\__init__.py", line 59, in _get_char_info
    im = await draw_char_info_img(msg, uid, ev.image)
  File "E:\zhenxun\gsuid_core\gsuid_core\plugins\StarRailUID\StarRailUID\starrailuid_charinfo\draw_char_img.py", line 78, in draw_char_info_img
    char_data = await get_char_data(sr_uid, char_name)
  File "E:\zhenxun\gsuid_core\gsuid_core\plugins\StarRailUID\StarRailUID\starrailuid_charinfo\draw_char_img.py", line 579, in get_char_data
    char_name = await alias_to_char_name(char_id, char_name)
  File "E:\zhenxun\gsuid_core\gsuid_core\plugins\StarRailUID\StarRailUID\utils\map\name_covert.py", line 24, in alias_to_char_name
    for i in alias_data['characters'][char_id]:
KeyError: ''

**Comment by 23650** [comment]
抱歉，是我触发指令有问题，希望大大能尽快更新'sr帮助'部分
