### ISSUE TITLE
与推送有关的功能都会报错。。。吧

### ISSUE THREAD

**Issue by Jerry-FaGe** [qwerdvd/StarRailUID#63]
看代码推送的键是 `stamina` 和 `go` ，但 core 的推送数据表里目前没有 `stamina` 相关的字段，而且 `go` 也跟原神的派遣冲突吧，是我那里操作不对导致数据库没写入么
```log
07-07 19:33:46 [INFO] gsuid_core.handler | [Trigger] 消息 「sr强制推送体力提醒」 触发 「fullmatch」 类型触发器, 关键词: 「sr强制推送体力提醒」
07-07 19:33:46 [INFO] gsuid_core.handler | [Command] command=sr强制推送体力提醒, text=
Task exception was never retrieved
future: <Task finished name='Task-4396' coro=<force_notice_job() done, defined at /home/Jerry_FaGe/nonebot_b/gsuid_core/gsuid_core/plugins/StarRailUID/StarRailUID/starrailuid_stamina/__init__.py:34> exception=KeyError('stamina_is_push')>
Traceback (most recent call last):
  File "/home/Jerry_FaGe/nonebot_b/gsuid_core/gsuid_core/plugins/StarRailUID/StarRailUID/starrailuid_stamina/__init__.py", line 37, in force_notice_job
    await sr_notice_job()
  File "/home/Jerry_FaGe/nonebot_b/gsuid_core/gsuid_core/plugins/StarRailUID/StarRailUID/starrailuid_stamina/__init__.py", line 42, in sr_notice_job
    result = await get_notice_list()
  File "/home/Jerry_FaGe/nonebot_b/gsuid_core/gsuid_core/plugins/StarRailUID/StarRailUID/starrailuid_stamina/notice.py", line 32, in get_notice_list
    msg_dict = await all_check(
  File "/home/Jerry_FaGe/nonebot_b/gsuid_core/gsuid_core/plugins/StarRailUID/StarRailUID/starrailuid_stamina/notice.py", line 54, in all_check
    if push_data[f'{mode}_is_push'] == 'on':
KeyError: 'stamina_is_push'
```

这是我查出的数据库
```python
{'bot_id': 'NoneBot2', 'coin_push': 'off', 'coin_is_push': 'off', 'resin_value': 140, 'go_push': 'off', 'go_value': 120, 'transform_push': 'off', 'transform_is_push': 'off', 'id': 2, 'coin_value': 2100, 'uid': '103426930', 'resin_push': 'on', 'resin_is_push': 'off', 'go_is_push': 'off', 'transform_value': 140}
```

**Comment by Jerry-FaGe** [comment]
https://github.com/qwerdvd/StarRailUID/blob/42f82956ecbbf8d119df3a5535c2eae81826fe87/StarRailUID/starrailuid_stamina/notice.py#L13-L16

实测把 stamina 修改为 resin ，然后手动修改 gspush 表开启推送，再然后修改 core 的 [update_push_data](https://github.com/Genshin-bots/gsuid_core/blob/067fde116cb037d992cefccd524e79dee8b91c04/gsuid_core/utils/database/dal.py#L372-L385) 方法可以**暂时**解决推送问题

```python
    async def update_push_data(
        self, uid: str, bot_id: str, data: dict
    ) -> bool:
        retcode = -1
        if await GsPush.data_exist(uid=uid):
            retcode = await GsPush.update_data_by_uid(
                # uid, self.bot_id, 'sr' if self.is_sr else None, **data
                uid, self.bot_id, None, **data
            )
        else:
            retcode = await GsPush.full_insert_data(
                uid=uid, bot_id=bot_id, **data
            )
        status = True if retcode == 0 else False
        return status
```

**Comment by qwerdvd** [comment]
感谢回复~~~~
这里是因为在 [`cb0f2f1`](https://github.com/qwerdvd/StarRailUID/commit/cb0f2f16e9bbddf88e6c94eeba569ef27936cb26#diff-06617e2449efc3fd8233232efa148c4ce54133b79afaa555c677530e1fb29486) 中将 `resin` 修改为了 `stamina`  导致的
但是忘记在数据库中做兼容，所以在这个commit之后创建的数据库其实都没有这个问题2333
anyway，晚点我会提供一个兼容方案，在数据库中新建 stamina 这一列

**Comment by Jerry-FaGe** [comment]
原来是这样😮
那可能还需要加一列 `sr_uid`
因为 core 的 [`e101d94`](https://github.com/Genshin-bots/gsuid_core/commit/e101d942a267dd9c3123e4a9ad079f46502bed87#diff-abb1af238b23ec9829283154ea8ea31242c04a835b6139d7e5d1727ef6ed09ad) 中修改了字段名的获取方式
`is_sr == True` 会导致先去搜索表中的 `sr_uid` 字段，我这里的老数据库中是没有这个字段的
上面评论对 core 的修改也是为了暂时适配这一改动

**Comment by KimigaiiWuyi** [comment]
> 原来是这样😮 那可能还需要加一列 `sr_uid` 因为 core 的 [`e101d94`](https://github.com/Genshin-bots/gsuid_core/commit/e101d942a267dd9c3123e4a9ad079f46502bed87#diff-abb1af238b23ec9829283154ea8ea31242c04a835b6139d7e5d1727ef6ed09ad) 中修改了字段名的获取方式 `is_sr == True` 会导致先去搜索表中的 `sr_uid` 字段，我这里的老数据库中是没有这个字段的 上面评论对 core 的修改也是为了暂时适配这一改动

从sruid诞生之初，启动core就会自动为没有sr_uid,sr_region,sr_sign_switch,sr_push_switch这几列的数据库自动添加列
应该不存在你说的老数据库没有这个字段

**Comment by Jerry-FaGe** [comment]
> 从sruid诞生之初，启动core就会自动为没有`sr_uid`,`sr_region`,`sr_sign_switch`,`sr_push_switch`这几列的数据库自动添加这几列 应该不存在你说的老数据库没有这个字段

你说的应该是 `gsuser` 表，这几个表确实是有这几个字段的；而我指的是 `gspush` 表，这个表目前在我这是没有 `sr_uid` 字段的， [`e101d94`](https://github.com/Genshin-bots/gsuid_core/commit/e101d942a267dd9c3123e4a9ad079f46502bed87#diff-abb1af238b23ec9829283154ea8ea31242c04a835b6139d7e5d1727ef6ed09ad) 的改动也会影响到这个表导致找不到字段的错误

ps: `sr_sign_switch` 和 `sr_push_switch` 这两列目前真的有在使用么，我没找到开启的命令，就算手动修改数据库貌似也没什么作用。我目前是手动修改了 `gspush` 表才正常开启了星铁的推送
- gsuser 表

  ![image](https://github.com/qwerdvd/StarRailUID/assets/40235071/1917fe62-224a-4b05-bfbe-ddf210f056ad)
- gspush 表

  ![image](https://github.com/qwerdvd/StarRailUID/assets/40235071/168dbd7f-b17a-4e5f-85f0-5c33d40ace3e)

**Comment by qwerdvd** [comment]
sr之后会另起一个push表
